"""added setting

Revision ID: 119ae43f5b3d
Revises: e4b27c82cc3d
Create Date: 2024-09-02 11:05:26.029982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119ae43f5b3d'
down_revision = 'e4b27c82cc3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromm', sa.Time(), nullable=False),
    sa.Column('to', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
