"""create global_ticket_counter table

Revision ID: 36efdf5a1335
Revises: 4e324d1fbc0f
Create Date: 2024-07-19 02:18:17.022342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36efdf5a1335'
down_revision = '4e324d1fbc0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
