"""asds

Revision ID: 6472c2a292b7
Revises: afadcaf50cd6
Create Date: 2024-07-18 22:18:14.903924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6472c2a292b7'
down_revision = 'afadcaf50cd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'window',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'window',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
