"""asd

Revision ID: 6aa4f0d358b3
Revises: a4d97d5a9853
Create Date: 2024-07-19 13:54:11.411244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa4f0d358b3'
down_revision = 'a4d97d5a9853'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
