"""update table ticket

Revision ID: a0e3f7bd786f
Revises: d4b1982d8b42
Create Date: 2024-08-04 19:05:43.470896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e3f7bd786f'
down_revision = 'd4b1982d8b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('tickets', sa.Column('phone_number', sa.String(), nullable=False))
    op.drop_column('tickets', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tickets', 'phone_number')
    op.drop_column('tickets', 'full_name')
    # ### end Alembic commands ###
