"""create global_ticket_counter table

Revision ID: a4d97d5a9853
Revises: f31a414fe81e
Create Date: 2024-07-19 02:24:36.939920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d97d5a9853'
down_revision = 'f31a414fe81e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
