"""FIXED

Revision ID: b04c3332b532
Revises: 6472c2a292b7
Create Date: 2024-07-19 02:03:14.496882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04c3332b532'
down_revision = '6472c2a292b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
