"""asd

Revision ID: d4b1982d8b42
Revises: 6aa4f0d358b3
Create Date: 2024-07-19 14:02:57.958449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b1982d8b42'
down_revision = '6aa4f0d358b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
