"""added setting

Revision ID: e4b27c82cc3d
Revises: a0e3f7bd786f
Create Date: 2024-09-02 11:03:31.385432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b27c82cc3d'
down_revision = 'a0e3f7bd786f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
