"""create global_ticket_counter table

Revision ID: f31a414fe81e
Revises: 36efdf5a1335
Create Date: 2024-07-19 02:21:09.474331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31a414fe81e'
down_revision = '36efdf5a1335'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
